#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sshuttle
Version  : 1.1.1
Release  : 1
URL      : https://github.com/sshuttle/sshuttle/archive/v1.1.1/sshuttle-1.1.1.tar.gz
Source0  : https://github.com/sshuttle/sshuttle/archive/v1.1.1/sshuttle-1.1.1.tar.gz
Summary  : Full-featured" VPN over an SSH tunnel
Group    : Development/Tools
License  : LGPL-2.1
Requires: sshuttle-bin = %{version}-%{release}
Requires: sshuttle-license = %{version}-%{release}
Requires: sshuttle-python = %{version}-%{release}
Requires: sshuttle-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(sphinx)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
sshuttle: where transparent proxy meets VPN meets ssh
=====================================================

%package bin
Summary: bin components for the sshuttle package.
Group: Binaries
Requires: sshuttle-license = %{version}-%{release}

%description bin
bin components for the sshuttle package.


%package license
Summary: license components for the sshuttle package.
Group: Default

%description license
license components for the sshuttle package.


%package python
Summary: python components for the sshuttle package.
Group: Default
Requires: sshuttle-python3 = %{version}-%{release}

%description python
python components for the sshuttle package.


%package python3
Summary: python3 components for the sshuttle package.
Group: Default
Requires: python3-core
Provides: pypi(sshuttle)
Requires: pypi(sphinx)

%description python3
python3 components for the sshuttle package.


%prep
%setup -q -n sshuttle-1.1.1
cd %{_builddir}/sshuttle-1.1.1
pushd ..
cp -a sshuttle-1.1.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1668453204
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sshuttle
cp %{_builddir}/sshuttle-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/sshuttle/01a6b4bf79aca9b556822601186afab86e8c4fbf
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sshuttle

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sshuttle/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
